services:
  gateway:
    build:
      context: .
      # برچسب‌های اضافی برای ایمیج هنگام بیلد
      tags:
        - sepidar-gateway:0.0.0
    image: sepidar-gateway:0.0.0
    container_name: sepidar-gateway
    restart: always
    ports:
      - "5259:5259" # نگاشت پورت کانتینر (پورت گیت‌وی) به پورت میزبان مورد نظر
    env_file:
      - ./env/${ASPNETCORE_ENVIRONMENT:-Production}/gateway.env # مسیر براساس مقدار ASPNETCORE_ENVIRONMENT انتخاب می‌شود
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5259/health/ready"]
      interval: 30s
      timeout: 5s
      retries: 3
    # بدون شبکه سفارشی؛ از شبکه پیش‌فرض داکر-کامپوز استفاده می‌شود
