version: "3.9"

services:
  gateway:
    build: .
    image: sepidar-gateway:latest
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      Gateway__Tenants__0__TenantId: docker
      Gateway__Tenants__0__Match__Header__HeaderName: X-Tenant-ID
      Gateway__Tenants__0__Match__Header__HeaderValues__0: docker
      Gateway__Tenants__0__Sepidar__BaseUrl: http://mock-sepidar:7373
      Gateway__Tenants__0__Sepidar__IntegrationId: 900900
      Gateway__Tenants__0__Sepidar__DeviceSerial: DOCKER-SERIAL
      Gateway__Tenants__0__Sepidar__GenerationVersion: 1.0.0
      Gateway__Tenants__0__Credentials__UserName: gateway
      Gateway__Tenants__0__Credentials__PasswordMd5: 0123456789ABCDEF0123456789ABCDEF
      Gateway__Tenants__0__Clients__ApiKeys__0: docker-key
      Gateway__Tenants__0__Jwt__CacheSeconds: 600
      Gateway__Tenants__0__Jwt__PreAuthCheckSeconds: 60
      Gateway__Tenants__0__Limits__RequestsPerMinute: 300
      Gateway__Tenants__0__Limits__QueueLimit: 50
      Gateway__Tenants__0__Limits__RequestTimeoutSeconds: 60
      Gateway__Ocelot__Routes__0__UpstreamPathTemplate: /api/{everything}
      Gateway__Ocelot__Routes__0__DownstreamPathTemplate: /api/{everything}
      Gateway__Ocelot__Routes__0__UpstreamHttpMethod__0: GET
      Gateway__Ocelot__Routes__0__UpstreamHttpMethod__1: POST
      Gateway__Ocelot__Routes__0__UpstreamHttpMethod__2: PUT
      Gateway__Ocelot__Routes__0__UpstreamHttpMethod__3: DELETE
      Gateway__Ocelot__Routes__0__UpstreamHttpMethod__4: PATCH
      Ocelot__Routes__0__UpstreamPathTemplate: /api/{everything}
      Ocelot__Routes__0__DownstreamPathTemplate: /api/{everything}
      Ocelot__Routes__0__UpstreamHttpMethod__0: GET
      Ocelot__Routes__0__UpstreamHttpMethod__1: POST
      Ocelot__Routes__0__UpstreamHttpMethod__2: PUT
      Ocelot__Routes__0__UpstreamHttpMethod__3: DELETE
      Ocelot__Routes__0__UpstreamHttpMethod__4: PATCH
    depends_on:
      mock-sepidar:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5000/health/ready"]
      interval: 30s
      timeout: 5s
      retries: 3

  mock-sepidar:
    image: wiremock/wiremock:3.5.4
    container_name: mock-sepidar
    ports:
      - "7373:7373"
    command: ["--port", "7373"]
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:7373/__admin" ]
      interval: 30s
      timeout: 5s
      retries: 3
